apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ldap-ui
  namespace: lab
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ldap-ui.__HOST_IP__.sslip.io
      secretName: ldap-ldaps-tls
  rules:
    - host: ldap-ui.__HOST_IP__.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: phpldapadmin
                port:
                  number: 80
