apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ldap-ldaps-cert
  namespace: lab
spec:
  secretName: ldap-ldaps-tls
  commonName: ldap.lab.svc.cluster.local
  subject:
    organizations:
      - Example Org
  issuerRef:
    name: lab-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - ldap.__HOST_IP__.sslip.io
    - ldap-ui.__HOST_IP__.sslip.io
    - ldap.lab.svc
    - ldap.lab.svc.cluster.local
